<a href="https://colab.research.google.com/github/tehjiajie6754/data_science_w2/blob/main/Tutorial03_WIX1007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#1. Create a numpy array of size 2 x 2
a = np.array([[1,2],[3,4]])
print(a.shape)
print(a)

(2, 2)
[[1 2]
 [3 4]]


In [ ]:
#2. Create a random numpy array of size 3 x 4
b = np.random.random((3,4))
print(b.shape)
print(b)

(3, 4)
[[0.54209384 0.65250637 0.3946527  0.20044364]
 [0.83412644 0.47572279 0.61748569 0.60134633]
 [0.1332052  0.31821049 0.29124722 0.3608142 ]]


In [ ]:
#3. Create a numpy array of ones and a numpy array of zeroes
c = np.ones((2,2))
d = np.zeros((2,2))
print(c)
print(d)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [ ]:
#4. Create a random numpy array of size 6x3 and transpose it
e = np.random.random((6,3))
print(e)
print("\nAfter transpose: ")
print(e.T)

[[0.51794421 0.01961174 0.56748548]
 [0.62977021 0.52081488 0.99319072]
 [0.34636406 0.38659728 0.01704319]
 [0.5468752  0.48215627 0.8561863 ]
 [0.44931911 0.21263889 0.68826398]
 [0.96225317 0.94565225 0.51706593]]

After transpose
[[0.51794421 0.62977021 0.34636406 0.5468752  0.44931911 0.96225317]
 [0.01961174 0.52081488 0.38659728 0.48215627 0.21263889 0.94565225]
 [0.56748548 0.99319072 0.01704319 0.8561863  0.68826398 0.51706593]]


In [12]:
#5. Create two random numpy array of size n x p and p x m and then compute the dot product
f = np.random.random((2,3))
g = np.random.random((3,4))
print(f)
print(g)
print("\nAfter dot product: ")
print(np.dot(f,g))

[[0.90589311 0.00729291 0.5629435 ]
 [0.33476447 0.57714672 0.95261509]]
[[0.56256088 0.5606212  0.52720585 0.41447643]
 [0.48565007 0.56422544 0.24045263 0.58296332]
 [0.90144779 0.44323127 0.77734458 0.96508855]]

After dot product: 
[[1.020626   0.76149189 0.91694682 0.92301316]
 [1.3273495  0.93554571 1.0557764  1.39456526]]
